spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}




server:
  server-url: ${SERVER_LOCAL_URL}
  front-urls: ${FRONT_PROD_URL}

