name: 'BE 이슈 생성'
description: 'BE Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [order]
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎫Epic Ticket Number'
      description: 'Epic의 Ticket Number를 기입해주세요'
      placeholder: 'SCRUM-0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '📋이슈 내용(Description)'
      description: '이슈에 대해서 자세히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '☑️체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: hidden
    id: taskType
    attributes:
      label: '🗃️업무 유형'
      description: 'Task'
      value: 'Task'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳브랜치 이름(Branch Name)'
      description: '해당 issue로 생성될 branch 이름을 기입해주세요'
      placeholder: '[type]/[branch-name]'
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: '📁참조(References)'
      description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
      value: |
        - Reference1
    validations:
      required: false
